spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartparking
    username: postgres
    password: Bala@sql
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: smart.parking.system.project@gmail.com
    password: gzda vama uhit zrjh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: 4E645267556A586E3272357538782F413F4428472B4B6250655368566D597133
    expiration-ms: 86400000
  mail:
    enabled: true                        # true = actually send emails
    from: noreply@smartparking.com
  super-admin:
    email: superadmin@smartparking.com
    password: SuperAdmin@123
    name: Super Admin
    phone: "9999999999"
  razorpay:
    enabled: true                        # ← set true after adding your keys
    key-id: rzp_test_T7saBCPuwu9dBK          # ← paste your Razorpay Test Key ID
    key-secret: uFocmeX2uLJtRc9XkTO9djAd           # ← paste your Razorpay Test Key Secret
    currency: INR

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.smart.parking: INFO
